# Generated by Django 5.0.2 on 2024-03-07 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'orgforms',
            },
        ),
        migrations.CreateModel(
            name='BisinessCard',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('ogrn', models.CharField(max_length=16, unique=True)),
                ('unic', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('kpp', models.CharField(max_length=16, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.address')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
                ('orgform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bisiness.orgform')),
            ],
            options={
                'db_table': 'bisiness_cards',
            },
        ),
    ]
