# Generated by Django 5.0.2 on 2024-03-07 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32, unique=True)),
                ('short_name', models.CharField(max_length=16, null=True)),
                ('int_code', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.country')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.locality')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=8, null=True)),
                ('district', models.CharField(max_length=32, null=True)),
                ('title', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=32)),
                ('house', models.CharField(max_length=32, null=True)),
                ('index', models.CharField(max_length=32, null=True)),
                ('flat', models.CharField(max_length=8, null=True)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.locality')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.region')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
    ]
