# Generated by Django 5.0.2 on 2024-03-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('living', models.BooleanField(default=False)),
                ('koef_price', models.FloatField()),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
