# Generated by Django 5.0.2 on 2024-03-07 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('patr_name', models.CharField(max_length=32, null=True)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BooleanField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'db_table': 'sex',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('series', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=8)),
                ('unic', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('police', models.CharField(max_length=256)),
                ('police_code', models.CharField(max_length=8)),
                ('dt_issue', models.DateField()),
                ('birth_place', models.CharField(max_length=128)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.address')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
            options={
                'db_table': 'passports',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.sex'),
        ),
    ]
