@startuml


hide class empty members

title 
	Недвижимость. Модели классов. 
end title
  
class EnergySave ##[bold]grey{
    Энергосбережение
	..
	+ name: CharField
}

class Seismic ##[bold]grey{
    Сейсмоустойчивость
	..
	+ name: CharField
}

class SaleStatus ##[bold]grey{
    Статус продажи
	..
	+ name: CharField
}

class LandPlot ##[bold]grey{
    Земельный участок
	..
    id: AutoField
    number: CharField
    square: FloatField
    usage: CharField
    owner_type: CharField
    owner_number: CharField
    owner_date: DateField
    owner_reg_number: CharField
    owner_reg_date: DateField
    document_egrn: DateField
}

class BuildingPermit ##[bold]grey{
    Разрешение на строительство
	..
	+ id: AutoField
	+ number: CharField
	+ dt_issue: DateField
	+ dt_expiry: DateField
	--
	+ land_plot: ForeignKey(LandPlot)
}

class HouseType ##[bold]grey{
    Тип жилого дома
	..
	+ id: AutoField
	+ name: CharField
}

class Microdistrict ##[bold]grey{
    Микрорайон
	..
	+ id: AutoField
	+ name: CharField
}

class House ##[bold]grey{
    Жилой дом
	..
	+ id: AutoField
	+ number: CharField
	--
	+ building_permit: ForeignKey(BuildingPermit)
	+ microdistrict: ForeignKey(Microdistrict)
	+ energy_save: ForeignKey(EnergySave)
	+ seismic: ForeignKey(Seismic)
	+ type: ForeignKey(HouseType)
	+ address: ForeignKey(Address)
}

class SectionPlan ##[bold]grey{
    Тип секции (подъезд)
	..
	+ id: AutoField
	+ name: CharField
	--
	+ floor_plan_name: ForeignKey(FloorPlan)
}

class Section ##[bold]grey{
    Секция (подъезд)
	..
	+ id: AutoField
	+ number: CharField
	--
	+ house: ForeignKey(House)
	+ section_plan: ForeignKey(SectionPlan)
}

class FloorPlan ##[bold]grey{
    План этажа
	..
	+ id: AutoField
	+ name: CharField
	--
	+ flat_plan_name: ForeignKey(FlatsPlan)
}

class Floor ##[bold]grey{
    Этаж
	..
	+ id: AutoField
	+ number: CharField
	--
	+ section: ForeignKey(Section)
	+ floor_plan: ForeignKey(FloorPlan)
}

class RoomType ##[bold]grey{
    Тип комнаты
	..
	+ id: AutoField
	+ name: CharField
	+ living: BooleanField
	+ koef_price: FloatField
}

class Room ##[bold]grey{
    Комната
	..
    + id: AutoField
    + square: FloatField
	--
    + flat: ForeignKey(Flat)
    + room_type: ForeignKey(RoomType)
}

class FlatsPlan ##[bold]grey{
    План квартиры
	..
	+ id: AutoField
	+ name: CharField
	+ square: FloatField
	--
	+ room_type: ForeignKey(RoomType)
}

class Flat ##[bold]grey{
    Квартрира
	..
	+ id: AutoField
	+ number: CharField
	--
	+ floor: ForeignKey(Floor)
	+ flat_plan: ForeignKey(FlatsPlan)
	+ status: ForeignKey(SaleStatus)
}

class Address ##[bold]grey{
    Адрес
	..
    + id: AutoField
    + contry_name: CharField
    + country_full_name: CharField
    + region: CharField
    + district: CharField
	+ locality: CharField
    + sity: CharField
    + street: CharField
    + home: CharField
    + flat: CharField
}

FlatsPlan      -[#grey,bold]u-o  RoomType 
FloorPlan      -[#grey,bold]u-o  FlatsPlan
SectionPlan    -[#grey,bold]u-o  FloorPlan

RoomType      o-[#grey,bold]r-    Room
FlatsPlan     o-[#grey,bold]r-    Flat
FloorPlan     o-[#grey,bold]r-    Floor
SectionPlan   o-[#grey,bold]r-    Section

Room          o-[#grey,bold]r-   Flat
Flat          o-[#grey,bold]r-   Floor
Floor         o-[#grey,bold]r-   Section
Section       o-[#grey,bold]r-   House   

Flat           -[#grey,bold]r-o  SaleStatus
BuildingPermit -[#grey,bold]d-o  LandPlot
House          -[#grey,bold]r-o  BuildingPermit
House          -[#grey,bold]d-o  EnergySave
House          -[#grey,bold]d-o  Seismic
House          -[#grey,bold]d-o  HouseType
House         o-[#grey,bold]u-   Microdistrict
House          -[#grey,bold]u-o   Address

@enduml
