@startuml

hide class empty members

scale 1200*800

title 
	Сделка ДДУ. Модели классов. 
end title

class OrgForm ##[bold]grey {
    Форма ЮЛ
    ..
	+ full_name: CharField[256]
    + short_name: CharField[16]
}
class Person ##[bold]grey {
	Персона
	..
    + last_name: CharField[64]
    + first_name: CharField[64]
    + patr_name: CharField[64]
    + sex: BooleanField
    + birthday: DateField
}
class Bank ##[bold]grey {
    Банк
	..
    + bik: CharField[16]
    + branch: CharField[128]
    + ks: CharField[32]
    + rs: CharField[32]
    + city: CharField[64]
    + address: CharField[128]
}
class Passport ##[bold]grey {
    Паспорт
	..
    + series: CharField[8]
    + number: CharField[8]
    + police_name: CharField[256]
    + police_code: CharField[16]
    + place_birth: CharField[256]
    + dt_issue: DateField
	--
    + address: ForeignKey(Address)
    + person: ForeignKey(Person)
    + bank: ForeignKey(Bank)
}
class BuisinessCard ##[bold]grey {
    Бизнес-карта
	..
    + full_name: CharField[256]
    + short_name: CharField[64]
    + inn: CharField[16]
    + kpp: CharField[16]
    + ogrn: CharField[16]
    + business: CharField[32]
    + site: CharField[64]
    + email: CharField[64]
    + director_power_type: CharField[32]
    + director_power_number: CharField[32]
    + director_power_date: DateField
	--
    + director: ForeignKey(Person)
    + address: ForeignKey(Address)
    + orgform: ForeignKey(OrgForm)
    + bank: ForeignKey(Bank)
}
class Client ##[bold]grey {
    Клиент
	--
    + passport: ForeignKey(Passport)
    + business: ForeignKey(BuisinessCard)
}


class Sale ##[bold]grey{
    Договор продажи
	..
    + number: CharField[32]
    + dt_issue: DateField
    + city: CharField[32]
    + price: FloatField
    + decoration: BooleanField
	--
    + flat: ForeignKey(Flat)
    + escrow_agent: ForeignKey(BuisinessCard)
}

class SaleClient ##[bold]grey{
    Сделки с клиентами
	..
    + part: FloatField
    + pay_days: CharField[3]
    + own_money: FloatField
    + credit_money: FloatField
	--
    + sale: ForeignKey(Sale)
    + client: ForeignKey(Client)
}
class Flat ##[bold]grey{}


OrgForm    *-[#grey,bold]u- BuisinessCard
Client      -[#grey,bold]-o  BuisinessCard
Client      -[#grey,bold]-*  Passport

Bank       o-[#grey,bold]u- BuisinessCard
Bank       o-[#grey,bold]- Passport
Person     o-[#grey,bold]r- BuisinessCard
Person     o-[#grey,bold]l- Passport

Sale        -[#grey,bold]r-o  Flat
Sale        -[#grey,bold]-o  BuisinessCard

SaleClient  -[#grey,bold]r-o Sale
SaleClient  -[#grey,bold]l-o Client


@enduml